on:
  # Trigger on push to the "main" branch or manual workflow dispatch
  push:
    branches: [ "main" ]
  workflow_dispatch:
  # Trigger on repository creation
  repository_dispatch:
    types: [repository_created]

jobs:
  update-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Fetch all repositories for the user
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user/repos?per_page=100 \
          | jq '.[] | {name, html_url}' > repos.json

      - name: Update the portfolio HTML
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html><body><h1>My Repositories</h1><ul>" >> index.html
          jq -r '.[] | "<li><a href=\"\(.html_url)\">\(.name)</a></li>"' repos.json >> index.html
          echo "</ul></body></html>" >> index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update portfolio with new repositories"
          git push