name: Update Portfolio

on:
  # Trigger on push to the "main" branch or manual workflow dispatch
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  update-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install jq (just in case)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch all public repositories
        run: |
          curl -s https://api.github.com/users/Gabriel2002Can/repos | jq '.[] | {name, html_url}' > repos.json

      - name: Update the portfolio HTML
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html><body><h1>My Public Repositories</h1><ul>" >> index.html
          jq -r '.[] | "<li><a href=\"\(.html_url)\">\(.name)</a></li>"' repos.json >> index.html
          echo "</ul></body></html>" >> index.html

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update portfolio with public repositories"
          git push