name: Update Portfolio

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  repository_dispatch:
    types: [repository_created]

jobs:
  update-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we fetch all commits

      - name: Fetch all public repositories
        run: |
          curl -s https://api.github.com/users/Gabriel2002Can/repos | jq -s '[.[][]]' > repos.json

      - name: Update the portfolio HTML with JS filter
        run: |
          echo "<!DOCTYPE html>" > index.html
          echo "<html><head><title>My Public Repositories</title>" >> index.html
          echo "<style>body { font-family: Arial, sans-serif; }</style>" >> index.html
          echo "</head><body>" >> index.html
          echo "<h1>My Public Repositories</h1>" >> index.html
          echo "<input type='text' id='filter' placeholder='Search repositories...' onkeyup='filterRepositories()'>" >> index.html
          echo "<div id='repositories'></div>" >> index.html

          # JavaScript to fetch and display data
          echo "<script>" >> index.html
          echo "const repos = $(cat repos.json);" >> index.html
          echo "const repositoriesContainer = document.getElementById('repositories');" >> index.html
          echo "const filterInput = document.getElementById('filter');" >> index.html

          # Function to render repositories
          echo "function renderRepositories(repos) {" >> index.html
          echo "  repositoriesContainer.innerHTML = '';" >> index.html
          echo "  repos.forEach(repo => {" >> index.html
          echo "    const div = document.createElement('div');" >> index.html
          echo "    div.classList.add('repo');" >> index.html
          echo "    div.innerHTML = `<h3><a href='${repo.html_url}' target='_blank'>${repo.name}</a></h3><p>${repo.description || 'No description available'}</p>`;" >> index.html
          echo "    repositoriesContainer.appendChild(div);" >> index.html
          echo "  });" >> index.html
          echo "}" >> index.html

          # Initial render
          echo "renderRepositories(repos);" >> index.html

          # Function to filter repositories based on the search input
          echo "function filterRepositories() {" >> index.html
          echo "  const searchTerm = filterInput.value.toLowerCase();" >> index.html
          echo "  const filteredRepos = repos.filter(repo => repo.name.toLowerCase().includes(searchTerm));" >> index.html
          echo "  renderRepositories(filteredRepos);" >> index.html
          echo "}" >> index.html

          echo "</script>" >> index.html
          echo "</body></html>" >> index.html

      - name: Commit any local changes before pulling
        run: |
          git add .
          git commit -m "Committing local changes before pull" || echo "No changes to commit"

      - name: Pull latest changes from remote (with rebase)
        run: |
          git fetch origin
          git checkout main
          git pull --rebase origin main  # Rebase to avoid merge commits

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update portfolio with public repositories"
          git push origin main